package com.handu.poweroperational.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.handu.poweroperational.db.entity.CommonBuildingAndDA;
import com.handu.poweroperational.db.entity.SearchContent;
import com.handu.poweroperational.db.entity.UserInfo;

import com.handu.poweroperational.db.dao.CommonBuildingAndDADao;
import com.handu.poweroperational.db.dao.SearchContentDao;
import com.handu.poweroperational.db.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonBuildingAndDADaoConfig;
    private final DaoConfig searchContentDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CommonBuildingAndDADao commonBuildingAndDADao;
    private final SearchContentDao searchContentDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonBuildingAndDADaoConfig = daoConfigMap.get(CommonBuildingAndDADao.class).clone();
        commonBuildingAndDADaoConfig.initIdentityScope(type);

        searchContentDaoConfig = daoConfigMap.get(SearchContentDao.class).clone();
        searchContentDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        commonBuildingAndDADao = new CommonBuildingAndDADao(commonBuildingAndDADaoConfig, this);
        searchContentDao = new SearchContentDao(searchContentDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CommonBuildingAndDA.class, commonBuildingAndDADao);
        registerDao(SearchContent.class, searchContentDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        commonBuildingAndDADaoConfig.clearIdentityScope();
        searchContentDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CommonBuildingAndDADao getCommonBuildingAndDADao() {
        return commonBuildingAndDADao;
    }

    public SearchContentDao getSearchContentDao() {
        return searchContentDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
